# Generated by Django 5.0.3 on 2025-02-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('amenity_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, null=True)),
                ('coordinates', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'amenities',
                'managed': False,
            },
        ),
    ]
