# Generated by Django 5.0.3 on 2025-02-07 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amenities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenities',
            options={'managed': False, 'verbose_name': 'Amenities', 'verbose_name_plural': 'Удобства'},
        ),
    ]
