# Generated by Django 5.0.3 on 2025-03-22 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_id', models.CharField(default=None, max_length=100, unique=True)),
                ('name', models.CharField(default='', max_length=255, verbose_name='Название')),
                ('url', models.URLField(default=None, max_length=500, verbose_name='Ссылка')),
                ('price', models.DecimalField(decimal_places=2, default=None, max_digits=10, verbose_name='Цена')),
                ('pricePerMeter', models.IntegerField(default=None, verbose_name='Цена за кв.м.')),
                ('photo', models.URLField(default=None, max_length=1000, verbose_name='Фото')),
                ('coordinates', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Координаты')),
                ('number_of_rooms', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Кол-во комнат')),
                ('total_area', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Общая площадь')),
                ('kitchen_area', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Площадь кухни')),
                ('floor', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Этаж')),
                ('balcony_or_loggia', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Балкон или лоджия')),
                ('bathroom', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Санузел')),
                ('windows', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Окна')),
                ('repair', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Ремонт')),
                ('furniture', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Мебель')),
                ('transaction_type', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Способ продажи')),
                ('technique', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Техника')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='buildings.buildings')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'managed': True,
            },
        ),
    ]
