# Generated by Django 5.0.3 on 2025-03-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcements',
            name='furniture',
        ),
        migrations.RemoveField(
            model_name='announcements',
            name='technique',
        ),
        migrations.RemoveField(
            model_name='announcements',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='announcements',
            name='ceiling_height',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=10, verbose_name='Высота потолков'),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='floor',
            field=models.IntegerField(default=None, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='kitchen_area',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=10, verbose_name='Площадь кухни'),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='number_of_rooms',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Кол-во комнат'),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='total_area',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=10, verbose_name='Общая площадь'),
        ),
    ]
