# Generated by Django 5.0.3 on 2025-03-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_remove_announcements_furniture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='ceiling_height',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=10, null=True, verbose_name='Высота потолков'),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='kitchen_area',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=10, null=True, verbose_name='Площадь кухни'),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='pricePerMeter',
            field=models.IntegerField(default=None, null=True, verbose_name='Цена за кв.м.'),
        ),
    ]
