# Generated by Django 5.0.3 on 2025-03-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_alter_announcements_ceiling_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='price',
            field=models.IntegerField(default=None, verbose_name='Цена'),
        ),
    ]
