# Generated by Django 5.0.3 on 2025-03-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_alter_announcements_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='announcement_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
