# Generated by Django 5.0.3 on 2025-04-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0005_alter_announcements_announcement_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
