# Generated by Django 5.0.3 on 2025-04-10 19:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0006_announcements_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
