# Generated by Django 5.0.3 on 2025-04-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0007_announcements_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='walk_score',
            field=models.IntegerField(blank=True, help_text='Оценка пешей доступности (0-100)', null=True, verbose_name='Walk Score'),
        ),
    ]
