# Generated by Django 5.0.3 on 2025-02-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('building_id', models.AutoField(primary_key=True, serialize=False)),
                ('address_text', models.TextField(blank=True, null=True)),
                ('district', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Район')),
                ('address_url', models.TextField(blank=True, null=True)),
                ('coordinates', models.TextField(blank=True, null=True, verbose_name='Координаты')),
                ('house_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип дома')),
                ('year_of_construction', models.CharField(blank=True, max_length=10, null=True, verbose_name='Год постройки')),
                ('number_of_floors', models.CharField(blank=True, max_length=10, null=True, verbose_name='Этажей в доме')),
                ('ceiling_height', models.CharField(blank=True, max_length=10, null=True, verbose_name='Высота потолков')),
                ('passenger_elevator', models.CharField(blank=True, max_length=50, null=True, verbose_name='Пассажирский лифт')),
                ('service_lift', models.CharField(blank=True, max_length=50, null=True, verbose_name='Грузовой лифт')),
                ('courtyard', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Двор')),
                ('parking', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Парковка')),
            ],
            options={
                'verbose_name': 'Buildings',
                'verbose_name_plural': 'Здания',
                'db_table': 'buildings',
            },
        ),
    ]
