# Generated by Django 5.0.3 on 2025-03-24 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buildings',
            old_name='service_lift',
            new_name='service_elevator',
        ),
    ]
