# Generated by Django 5.0.3 on 2025-03-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_rename_service_lift_buildings_service_elevator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildings',
            name='number_of_floors',
            field=models.IntegerField(default=None, verbose_name='Этажей в доме'),
        ),
    ]
