# Generated by Django 5.0.3 on 2025-04-16 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0004_buildingamenities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildingamenities',
            options={'verbose_name': 'building_amenities', 'verbose_name_plural': 'Связь здания и удобства'},
        ),
        migrations.RemoveField(
            model_name='buildings',
            name='address_url',
        ),
    ]
